#!/usr/bin/env php
<?php
/**
 * Runs extension manager
 *
 * @author Craig Campbell
 */
use Sonic\Extension\Manager;
use Sonic\App;

$base_path = str_replace(DIRECTORY_SEPARATOR . 'util', '', __DIR__);
require $base_path . DIRECTORY_SEPARATOR . 'libs' . DIRECTORY_SEPARATOR . 'Sonic' . DIRECTORY_SEPARATOR . 'App.php';
$app = Sonic\App::getInstance();
$app->setBasePath($base_path);
$app->includeFile('Sonic/Extension/Manager.php');

try {
    $app->start(App::COMMAND_LINE);
    Manager::start($_SERVER['argv']);
} catch (\Exception $e) {
    echo $e->getMessage(),"\n";
}
